### ISSUE TITLE
How can I make it more robust

### ISSUE THREAD

**Issue by jiayaozhang** [MarcoAttene/CDT#6]
Thanks for your great work!

I wan to test CDT and want to use it in physics games scenario.

But when I try 

```
 .\cdt.exe .\tempin.off
Assertion failed: tetIntersectsFace(t, f), file D:\Janice_Research\CDT\src\PLC.cpp, line 1195
```

Then I use to VolumeMesher to make Robust Solid mesh as below

But it still fail to use the CDT

```
 .\cdt.exe -mbfr .\black_faces.off
Non-triangular faces not supported
```
[CDT.zip](https://github.com/MarcoAttene/CDT/files/15092446/CDT.zip)

Can you help with this?
Many thanks!

**Comment by MarcoAttene** [comment]
The problem is that your model is not a valid input to CDT because it self-intersects. Using VolumeMesher to fix it may help, but as you could see it produces non-triangular faces which are not supported in CDT.
My suggestion is to fix your model using MeshFix and then pass the result to CDT. This may distort your model a little bit, but the procedure is guaranteed robust.
